### ISSUE TITLE
update icons

### ISSUE THREAD

**Issue by pelikhan** [brainpad-board/brainpad-pulse#39]
![image](https://user-images.githubusercontent.com/4175913/141664137-7b855895-71ea-4709-a408-5db1356b4acf.png)

**Comment by Palomino34** [comment]
Any idea about this? We updated icon and run local host, it load icon correctly. But build static then pick different icon.

**Comment by pelikhan** [comment]
You can override the appmeta.html file in /docfiles to define all the social headers
https://github.com/microsoft/pxt/blob/master/docfiles/appmeta.html
